apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: blackrock
  description: The blackrock organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: BlackRcok
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [aladdin]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: blackrock-groups
  description: A collection of all BLK example Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
    - ./team-c-group.yaml
    - ./team-d-group.yaml
